### ISSUE TITLE
Determining version of MUMPS

### ISSUE THREAD

**Issue by jsgrahamus** [joelivey/M-Unit#5]
I've noticed that, in the KID file, the version of MUMPS in use is determined by +$SY:  0 is Cache and 47 is GT.M .

Turns out that this only worked for part of our group.  The other part - myself included - had PC's with $SY which started with a number (62 in my case, which corresponded to the first 2 digits of my Window 10's Computer name).  Fortunately it wasn't 47! 

For now, I've changed the logic in our version so that 47 indicates GT.M, otherwise it's Cache. 

Is there a better way of determining which version of MUMPS is running? 

Thanks so much for developing this and sharing it with others.

Steve Graham 
[MASH_1P4.KID.txt](https://github.com/joelivey/M-Unit/files/627915/MASH_1P4.KID.txt)

(jsgrahamus@yahoo.com)

**Comment by jsgrahamus** [comment]
When I asked about this issue on the comp.lang.mumps newsgroup, I got a reply from Ray Newman, the creator of MUMPS V1:

According to the standard, $SY is V,S where V is an integer value allocated by the MDC to an implementor and S is defined by that implementor in such a way as to be able to be unique for all the implementor’s systems.  My implementation was assigned 50 by MDC hence returns 50,version specific information (eg: "50,MUMPS V1.66 for Linux armv7l Built Feb 26 2016 at 23:51:33" or "50,MUMPS V1.67 for Darwin x86_64 Built Aug 23 2016 at 07:28:09". 

Older versions of MUMPS used $ZV for a similar purpose

**Comment by jsgrahamus** [comment]
Oops, did not mean to close issue.

**Comment by joelivey** [comment]
Until you pointed this out to me, I was not aware of the MUMPS V1 version on GitHub, so it currently works only with the Cache and GT.M versions of MUMPS.  I will have to do some testing to see how much modification is required to support V1 as well.  Thanks for the input.

**Comment by jsgrahamus** [comment]
Glad to help

**Comment by shabiel** [comment]
I am the author of the $SY code. Let me explain:

$SY is the standard way of identifying M systems; however, Intersystems, as
is their way, decided to not implement it; and thus it doesn't return a
valid value anymore. $ZV is not standard; and would fail on MV1. I think we
can though use an anonymous do block and onion peeling in order to do $ZV
on Cache, and $SY on everything else.

On MV1: I actually wrote some C code for it (the $TEXT re-implementation is
mine, as it previously didn't cover all cases); and I wrote the current
makefile I authored. I am writing code to support it in VPE and Fileman;
but I am stuck at making sure the terminators work for F keys. Look for
Fileman and MV1 in comp.lang.mumps.

The official MV1 is at mumps.sourceforge.net; the github repo is by
somebody who forked the project in a way I do not support. He has done some
wonderful things, but he also added a lot of Z commands, which MV1 does not
have. MV1 basically is a purist MUMPS, trying to be completely M95
compliant.

Back to M-Unit: I am not currently working on it; but I have some code I
need to give Joel that does timing of tests in microseconds.

--Sam

**Comment by jsgrahamus** [comment]
Very interesting, Sam.  Thanks for the info and what you've done.  I noticed your name on Joel's project and/or on the Boyone version.

**Comment by joelivey** [comment]
The newest version (MASH*1.5*0) that was just uploaded to GitHub does take care of this issue, insuring that the name of the windows computer will not affect the identification of a Cache system.  Thank you for bringing this to our attention.  Joel Ivey
